Kadai
Tampoka/test pull request #1
Opened 2022-11-30 04:53 UTC by Tampoka

Review お願いいたします。

2022-12-01 08:10 UTC, aganomaminmi requested changes
@Olga-dot-art 
実装ありがとうございました！！
爆速で開発していただけて、さすがとしか言いようがありません。

実装も大きな問題もそこまでなかったので、細かいところをもうちょっと詰めてみましょう！
コメントしてみたので、確認をお願いします！

2022-12-01 08:10 UTC, aganomaminmi commented on src/index.tsx
> +    <App/>
基本 Strict Mode を使いながら開発した方がクオリティが担保できると思うのですが、オフにした理由ってありますか？

2022-12-01 08:10 UTC, aganomaminmi commented on src/hooks/useFetching.ts
> +export const useFetching = (callback: (...args: any[]) => void) => {
```
): [(...args: T) => Promise<void>, boolean, string] => {
```

みたいな感じで、custom hook の返り値も指定することができます！
ヒューマンエラーを防いだり、型補完を効かせるために基本は指定しましょう！

また、
```
return {
  fetch,
  isLoading,
  error,
}
```
のように、hooksが返す値はオブジェクトでも良いと思います！

2022-12-01 08:10 UTC, aganomaminmi commented on src/hooks/useFetching.ts
> +    const fetching = async (...args: any[]) => {
TypeScriptのジェネリクスを使って、ここの型も制限することができます。

エラーを防ぐために、基本はany型使わないように心がけましょう！

2022-12-01 08:10 UTC, aganomaminmi commented on src/components/PostItem/PostItem.module.scss
> +.itemWrapper {
綺麗にレイアウト作れていて素晴らしいです！
デザイン通りでとても良いと思います！

なので今回はレスポンシブも少し対応してみましょうか。
maxのwidthはスマートフォンの画面幅で指定しつつ、`320px`くらいの画面幅まで同じようにレイアウトを保ちつつ表示できるようにやってみてください！

お願いします！

2022-12-01 08:10 UTC, aganomaminmi commented on src/api/config.ts
> +import axios from 'axios';
fetchロジックの共通化、素晴らしいです！

使いまわせるようにできていて良いと思います！
あとは、 `posts-api.ts` だったりはアプリを構築していく上でエンドポイントが増えていったりした時に何のpostかわからなくなってしまうと思うので、それを踏まえてファイル分けと命名を行うと良いと思います。

2022-12-01 08:10 UTC, aganomaminmi commented on src/components/SettingsPanel/SettingsPanel.module.scss
> +.wrapper {
flex box や stickyを綺麗に使えていて素晴らしいです！

2022-12-01 08:10 UTC, aganomaminmi commented on src/components/SettingsPanel/SettingsPanel.tsx
> +            <img src={HomeImg} alt="" width={48} height={48}/>
width と height の指定、しっかりできてますね。意外と大事なところなので助かります！

2022-12-01 08:10 UTC, aganomaminmi commented on src/App.tsx
> +        // @ts-ignore
ts-ignoreは使わないように実装しましょう！
うまくジェネリクスを利用したり、実装の形を変えることで使わずに済むと思います！

useFetchingのところでコメントしているので、やってみてください！

どうしてもわからなかったらお手伝いするので、その時は呼んでください！

2022-12-01 08:10 UTC, aganomaminmi commented on src/App.tsx
> +        const response = await postsApi.getPosts()
post と useStateも問題ないですね！

2022-12-01 08:10 UTC, aganomaminmi commented on src/App.tsx
> +            // @ts-ignore
ここも型つけられます！やってみましょう

2022-12-01 08:10 UTC, aganomaminmi commented on src/hooks/useSortedPosts.ts
> +import {PostType} from '../types/types';
LGTM

2022-12-01 08:10 UTC, aganomaminmi commented on src/types/types.ts
> +export type PostType = {
typeについても、扱う型が増えてきた時に管理が大変になるので、ファイル分けと適した命名をしましょう！

2022-12-02 11:57 UTC, Tampoka commented on src/hooks/useFetching.ts
> +    const fetching = async (...args: any[]) => {
限定をせずですと、
`export const useFetching = (callback: { <T>(...args: T[]) : Promise<void> }): [{ <T>(...args: T[]): Promise<void> }, boolean, string] =>`
という感じになります。同じAnyですが、コードが複雑になるだけです。
限定をすると、
 const useFetching = (callback: { (...args: Optional<number | string>[]): Promise<void> }): [{ (...args: Optional<number | string>[]): Promise<void> }, boolean, string]
となります。

2022-12-02 12:02 UTC, Tampoka commented on src/index.tsx
> +    <App/>
ええと、double renderの原因を探した中でオフになったままになってしまいました。

2022-12-02 12:04 UTC, Tampoka commented on src/hooks/useFetching.ts
> +export const useFetching = (callback: (...args: any[]) => void) => {
Returning valueの指定を忘れないようにしたいと思います。

2022-12-02 12:07 UTC, Tampoka commented on src/components/PostItem/PostItem.module.scss
> +.itemWrapper {
ありがとうございます。
レスポンシブ対応してみました。

2022-12-02 12:08 UTC, Tampoka commented on src/App.tsx
> +        // @ts-ignore
反省しております。

2022-12-02 12:10 UTC, Tampoka commented on src/api/config.ts
> +import axios from 'axios';
大きなプロジェクトのfolder structure を勉強します

2022-12-05 03:34 UTC, aganomaminmi commented on src/index.tsx
> +    <App/>
なるほど確かにdouble renderされますね！

想定していない副作用を顕在化させるために、わざとdouble renderさせているみたいですね。
本番環境では一回だけrenderされるようになるのかな？と思います。

double renderがあると開発ができない場合を除いて、基本はOnでいいと思いますが、オリガさんはどう思いますか？

2022-12-05 03:44 UTC, aganomaminmi commented on src/api/config.ts
> +import axios from 'axios';
ごめんなさい、僕が勘違いしていたみたいです。
postsは投稿一覧、と言うことなのですね。

apiのエンドポイントが 'photo' なので、写真一覧みたいな命名になると思ってました。
それで言うと前回のものでよかったですね。すみません。
```
src
├─ api
│  ├─ config.ts
│  ├─ posts.ts
│  └─ other-posts.ts
```

こんな感じでエンドポイントごとにファイルを増やしていく想定ですよね。良いと思います！

2022-12-05 03:56 UTC, aganomaminmi commented on src/hooks/useFetching.ts
> +    const fetching = async (...args: any[]) => {
これ、もう少し強めに制限かけることもできて、返される fetch function の引数でも補完を効かせることができるようになります。
あまりgenericsを使う機会はないとは思いますが、汎用的な関数を使う時に知っていると便利なので、興味があれば勉強してみてください！
```
export const useFetching = <T extends any[]>(callback: {
  (...args: T): Promise<void>;
}): [
  { (...args: T): Promise<void> },
  boolean,
  string
] => {
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState("");

  const fetching = async (
    ...args: T
  ): Promise<void> => {
    try {
      setIsLoading(true);
      await callback(...args);
    } catch (e: any) {
      setError(e.message);
    } finally {
      setIsLoading(false);
    }
  };
  return [fetching, isLoading, error];
};
```

2022-12-05 04:34 UTC, aganomaminmi requested changes
コメントしました！！！ほぼほぼ完璧かと思います！
一点だけコメントしたので、確認していただけると嬉しいです！

2022-12-05 04:34 UTC, aganomaminmi commented on src/components/PostItem/PostItem.module.scss
> +    img {
画像は、レスポンシブした時にアスペクト比がコンテナと一緒に変化して、画像が引き伸ばされてしまうことがあります。引き伸ばされるとデザイン的に out になってしまうことがあるので、基本はobject-fitを指定して引き伸ばされるようにするか、heightを外すかするのが良いと思います。
(大体の場合はobject-fitが良いと思います。)

2022-12-05 04:41 UTC, Tampoka commented on src/components/PostItem/PostItem.module.scss
> +    img {
ありがとうございます！
aspect-ratioを調整しないとだめですね。

2022-12-05 06:31 UTC, Tampoka commented on src/components/PostItem/PostItem.module.scss
> +    img {
object-fit: cover; で調整しました。

2022-12-05 13:12 UTC, Tampoka commented on src/index.tsx
> +    <App/>
基本的にONであるはずと思います。
開発モードの場合にのみdouble renderされるということですね。

2022-12-06 01:51 UTC, aganomaminmi commented on src/index.tsx
> +    <App/>
OKです！その方針でいきましょう！

> 開発モードの場合にのみdouble renderされるということですね。

そうだと思います！

2022-12-06 05:25 UTC, aganomaminmi approved these changes
@Tampoka 
LGTM!!

素晴らしいです！コードはもちろん素晴らしいですし、レビューももれなく対応していただけてとても良いと思います！！！
githubはmarkdownでコメントできますが、それはちょっとずつ覚えていけば大丈夫です！特にテキストを見やすくしなくてもレビューはできると思うので！

ありがとうございました！マージしちゃいましょう！

2022-12-06 05:25 UTC, aganomaminmi commented on src/components/PostItem/PostItem.module.scss
> +    img {
うん、いいですね！！！完璧だと思います！

2022-12-06 06:00 UTC, merged